// angular-client/src/app/posts/post-details/post-details.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-post-details',
  templateUrl: './post-details.component.html',
  styleUrls: ['./post-details.component.scss']
})
export class PostDetailsComponent {
  @Input() post!: any;

}

<div class="post">
    <a class="post__link" href="posts/{{post._id}}">
        <img class="post__cover" [src]="post.coverPath" alt="cover" />
        <div class="post__infos">
            <div class="info">
                <p>le <span class="info__date">{{ post.updatedAt | date }}</span></p>
                <p>par <span class="info__author">{{ post.author.fullName}} </span></p>
                <span><span class="info__likes">{{ post.likes.length }}</span> like(s)</span>
            </div>
            <h3>{{ post.title }}</h3>
            <p class="summary">{{ post.summary }}</p>
        </div>
    </a>
</div>

// react-client/src/components/PostDetails.js
import { Link } from "react-router-dom";
import { format } from "date-fns";

const PostDetails = ({ post }) => {
    const likes = post.likes ? post.likes.length : 0;
    console.log(likes);

    const date = post.createdAt ? format(new Date(post.createdAt), 'd MMM yy') : 'N/A';

    return (
        <div className="post">
            <Link className="post__link" to={`/post/${post._id}`}>
                <img className="post__cover" src={post.coverPath} alt="cover" />
                <div className="post__infos">
                    <div className="info">
                        <p>le <span className="info__date">{date}</span></p>
                        <p>par <span className="info__author">{post.author.fullName}</span></p>
                        <span><span className="info__likes">{likes}</span> like(s)</span>
                    </div>
                    <h3>{post.title}</h3>
                    <p className="summary">{post.summary}</p>
                </div>
            </Link>
        </div>
    );
}

export default PostDetails;
